# Generated by Django 5.2.7 on 2026-07-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_make_lesson_video_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='duration',
            field=models.CharField(blank=True, help_text='Lesson duration, e.g. 12:30', max_length=20),
        ),
    ]
