# Generated by Django 5.2.7 on 2026-07-07 10:41 (patched to use existing reference_lesson_id column)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_userlessonnote'),
    ]

    operations = [
        # explanation column already exists in DB (added by a prior squashed migration)
        # related_lesson maps to the existing reference_lesson_id column via db_column
        migrations.AlterField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='Shown to the learner after they answer, regardless of correctness.'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='related_lesson',
            field=models.ForeignKey(
                blank=True,
                db_column='reference_lesson_id',
                help_text='Course lesson to review if the learner wants to study this topic further.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='quiz_questions',
                to='courses.courselesson',
            ),
        ),
        migrations.DeleteModel(
            name='UserLessonNote',
        ),
    ]
