# Generated by Django 5.2.7 on 2026-07-17 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_quizquestion_explanation_and_more'),
        ('courses', '0016_delete_userlessonnote'),
    ]

    operations = [
    ]
