# Generated by Django 5.2.7 on 2026-07-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_merge_20260717_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allow_purchase',
            field=models.BooleanField(default=True, help_text='If disabled, the course stays visible but cannot be purchased/enrolled in.'),
        ),
    ]
