# Generated by Django 5.2.7 on 2026-07-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_course_allow_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('youtube_url', models.URLField(max_length=1200)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_deleted', 'is_active'], name='courses_fre_is_dele_31f4cb_idx')],
            },
        ),
    ]
