# Generated by Django 5.2.7 on 2026-08-12 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_freecourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeCourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('free_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.freecourse')),
            ],
            options={
                'ordering': ['free_course_id', 'module_number'],
                'unique_together': {('free_course', 'module_number')},
            },
        ),
        migrations.CreateModel(
            name='FreeCourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('youtube_url', models.URLField(max_length=1200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.freecoursemodule')),
            ],
            options={
                'ordering': ['module_id', 'lesson_number'],
                'unique_together': {('module', 'lesson_number')},
            },
        ),
    ]
