# Generated by Django 5.2.7 on 2026-08-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_freecoursemodule_freecourselesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='freecourselesson',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1200),
        ),
    ]
