# Generated by Django 5.2.7 on 2026-06-30 09:41

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Source document or reference name (e.g. filename.pdf)', max_length=255)),
                ('chunk_index', models.IntegerField(help_text='Sequence index of the split chunk')),
                ('content', models.TextField(help_text='Grounded text content representing the chunk')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384, help_text='Vector embedding values representing semantic meaning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chatbot_document_embedding',
            },
        ),
    ]
